#!/bin/bash

echo "Generate EVM OPCODE/Gwei Specification"
sleep 1
curl https://raw.githubusercontent.com/trailofbits/evm-opcodes/master/README.md --output evm-opcodes.md
kramdoc --lazy-ids evm-opcodes.md

echo "The new appendix for OPCODES and Gwei was autogenerated succesfully!"

exit 0
