version: 2

job_common: &job_common
  docker:
    - image: circleci/node:10.12-stretch
  working_directory: ~/contracts
step_save_cache: &step_save_cache
  save_cache:
    paths:
      - ~/.cache/package-lock
    key: node-modules-{{ checksum "package-lock.json" }}
step_restore_cache: &step_restore_cache
  restore_cache:
    keys:
      - node-modules-{{ checksum "package-lock.json" }}
step_setup_global_packages: &step_setup_global_packages
  run:
    name: "Set up global packages"
    command: |
      npm install
jobs:
  unit-test:
    <<: *job_common
    steps:
      - checkout
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Lint Solidity contracts"
          command: npm run lint:contracts
      - run:
          name: "Compiling external library contracts"
          command: npm run compile:lib
      - run:
          name: "Compiling contracts"
          command: npm run compile
      - run:
          name: "Lint JavaScript"
          command: npm run lint:js
      - run:
          name: "Running unit tests"
          command: npm run ganache >/dev/null 2>&1 & npm run test
      - run:
          name: "Testing deployment scripts"
          command: npm run ganache >/dev/null 2>&1 & npm run test:deployment
      - run:
          name: "Running coverage"
          command: npm run test:coverage
      - <<: *step_save_cache
      # Save coverage artifacts
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  commit:
    jobs:
      - unit-test
